export { LoginPage } from './LoginPage'
export { DashboardPage } from './DashboardPage'
export { IncidentsPage } from './IncidentsPage'
export { MapPage } from './MapPage'
export { EquipmentPage } from './EquipmentPage'
export { SettingsPage } from './SettingsPage'
export { PreventivePage } from './PreventivePage'
export { HierarchyPage } from './HierarchyPage'
export { PhotoEvidencePage } from './PhotoEvidencePage'
export { PredictivePage } from './PredictivePage'
export { SensorsPage } from './SensorsPage'
export { RepuestosDashboard } from './repuestos/Dashboard'
export { PermissionsPage } from './admin/PermissionsPage'
export { Visor3DListPage, Visor3DViewerPage } from './Visor3D'
export { CalendarioMantencionPage } from './CalendarioMantencionPage'
export { HmiKnuroPage } from './HmiKnuroPage'
export { Baader200LearningPage } from './Baader200LearningPage'
